services:
  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      OLLAMA_URL: ${OLLAMA_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
    depends_on:
      - weaviate
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/ui
    environment:
      BACKEND_URL: http://app:8000
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: true
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: none
      CLUSTER_HOSTNAME: weaviate
      ENABLE_GRPC: true
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
